# File written on 2026-02-24 16:54:47.808906 
# Vega git hash: 9f56a6467d08754790c967f9847db69081000df5 

[data]
name = lyaxlya
tracer1 = LYA
tracer2 = LYA
tracer1-type = continuous
tracer2-type = continuous
filename = /global/cfs/cdirs/desi/science/lya/y3-fs/validation-tests/v1-1-0-0/baseline/correlations/results/lyalya_lyalya/cf_exp.fits.gz
distortion-file = /global/cfs/cdirs/desi/science/lya/y3-fs/validation-tests/v1-1-0-0/baseline/correlations/results/lyalya_lyalya/dmat.fits.gz
weights-tracer1 = /global/cfs/cdirs/desi/science/lya/y3-fs/validation-tests/v1-1-0-0/baseline/deltas/results/lya/Log/delta_attributes.fits.gz
weights-tracer2 = /global/cfs/cdirs/desi/science/lya/y3-fs/validation-tests/v1-1-0-0/baseline/deltas/results/lya/Log/delta_attributes.fits.gz

[cuts]
rp-min = -300
rp-max = +300.
rt-min = 0
rt-max = 300.
r-min = 30
r-max = 180
mu-min = -1
mu-max = 1

[model]
z evol LYA = bias_vs_z_std
small scale nl = dnl_arinyo
use_metal_autos = True
desi-instrumental-systematics = True
model-hcd = Rogers2018
fast_metals = True
new_metals = True
rp_only_metal_mats = False
marginalize-below-rtmax = 16
marginalize-above-rtmin = 0
marginalize-below-rpmax = 4
marginalize-above-rpmin = 0
marginalize-all-rmin-cuts = False
skip-nl-model-in-peak = False

[metals]
filename = None
z evol = bias_vs_z_std
in tracer1 = SiII(1190) SiII(1193) SiIII(1207) SiII(1260) CIV(eff)
in tracer2 = SiII(1190) SiII(1193) SiIII(1207) SiII(1260) CIV(eff)

[metal-matrix]
rebin_factor = 3
alpha_LYA = 2.9
alpha_SiII(1260) = 1.
alpha_SiIII(1207) = 1.
alpha_SiII(1193) = 1.
alpha_SiII(1190) = 1.
alpha_CIV(eff) = 1
z_ref_objects = 2.25
z_evol_objects = 1.44
z_bins_objects = 1000

