# File written on 2026-02-24 16:54:47.816188 
# Vega git hash: 9f56a6467d08754790c967f9847db69081000df5 

[data sets]
zeff = 2.33
ini files = lyaxlya-fit_mc.ini lyaxlyb-fit_mc.ini lyaxqso-fit_mc.ini lybxqso-fit_mc.ini
global-cov-file = /global/cfs/cdirs/desi/science/lya/y3-fs/validation-tests/v1-1-0-0/baseline/fits/results/full-covariance-smoothed.fits

[cosmo-fit type]
cosmo fit func = phi_alpha
full-shape = False
full-shape-alpha = False
smooth-scaling = True

[fiducial]
filename = Planck18/DESI-2024_z_2.33.fits

[output]
filename = /global/cfs/projectdirs/desi/users/acuceu/notebooks_perl/desi-y3-fs/baseline_tests/monte_carlo/output_fitter/lyaxlya_lyaxlyb_lyaxqso_lybxqso-fit_mc
mc_output = /global/cfs/projectdirs/desi/users/acuceu/notebooks_perl/desi-y3-fs/baseline_tests/monte_carlo/output_fitter/monte_carlo_fits

[sample]

[priors]
drp_QSO = gaussian 0.0 0.1
beta_hcd = gaussian 0.50 0.09
L0_hcd = gaussian 5.0 2.0
bias_CIV(eff) = gaussian -0.019 0.005
bias_QSO = gaussian 3.4 0.2
sigma_velo_disp_lorentz_QSO = gaussian 5.21 0.85

[parameters]
phi = 1.0
alpha = 1.0
phi_smooth = 1.0
alpha_smooth = 1.0
sigmaNL_per = 3.24
sigmaNL_par = 6.36984
bao_amp = 1.
bias_LYA = -0.16926780982979264
beta_LYA = 1.2224556494374903
alpha_LYA = 2.9
bias_QSO = 3.4
bias_eta_QSO = 1
growth_rate = 0.97
alpha_QSO = 1.44
dnl_arinyo_q1 = 0.303
dnl_arinyo_q2 = 0.267
dnl_arinyo_kv = 0.576
dnl_arinyo_av = 0.443
dnl_arinyo_bv = 1.66
dnl_arinyo_kp = 11.062
bias_hcd = -0.0015797865242653236
beta_hcd = 0.5
L0_hcd = 5.0
drp_QSO = 0.0
sigma_velo_disp_lorentz_QSO = 5.21
qso_rad_strength = 7.994484408443579e-07
qso_rad_asymmetry = 0.
qso_rad_lifetime = 9e99
qso_rad_decrease = 300.
bias_SiII(1190) = -0.0034674632722751005
beta_SiII(1190) = 0.5
alpha_SiII(1190) = 1.
bias_SiII(1193) = -0.0028780835995535804
beta_SiII(1193) = 0.5
alpha_SiII(1193) = 1.
bias_SiIII(1207) = -0.011336859356325469
beta_SiIII(1207) = 0.5
alpha_SiIII(1207) = 1.
bias_SiII(1260) = -0.0032790611775395245
beta_SiII(1260) = 0.5
alpha_SiII(1260) = 1.
bias_CIV(eff) = -0.019721635650474394
beta_CIV(eff) = 0.5
alpha_CIV(eff) = 0.
desi_inst_sys_amp = 0.00022327196072759474

[control]
run_sampler = True
use_template_growth_rate = False
sampler = Polychord
low_mem_mode = False

# Monte Carlo settings
run_montecarlo = True
forecast = False
mc_mocks = /global/cfs/cdirs/desi/users/acuceu/notebooks_perl/desi-y3-fs/baseline_tests/monte_carlo/output_fitter/monte_carlo/monte_carlo.fits

[Polychord]
path = /global/cfs/projectdirs/desi/users/acuceu/notebooks_perl/desi-y3-fs/baseline_tests/monte_carlo/output_sampler
name = lyaxlya_lyaxlyb_lyaxqso_lybxqso-fit_mc
num_live = 448
num_repeats = 20
do_clustering = True
boost_posterior = 0

[mc parameters]

[monte carlo]
alpha = True
phi = True
phi_smooth = True
alpha_smooth = True
bias_LYA = True
beta_LYA = True
bias_QSO = True
growth_rate = True
sigma_velo_disp_lorentz_QSO = True
drp_QSO = True
qso_rad_strength = True
bias_hcd = True
beta_hcd = True
L0_hcd = 0.0 10.0
bias_SiII(1190) = True
bias_SiII(1193) = True
bias_SiIII(1207) = True
bias_SiII(1260) = True
bias_CIV(eff) = True
desi_inst_sys_amp = True

